#!/usr/bin/env bash
# Install Nginx on web server and configure it to return 'Hello World!' at the root

sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create 'Hello World!' content in the default Nginx root directory
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# Start Nginx service
sudo service nginx start
