#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Redirects to another page
# Have a custom 404 page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
ADD404_NOTFOUND="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

# Add redirect configuration at line 30 in the default Nginx configuration
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default

# Create custom_404.html content in the default Nginx root directory
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Uncomment and replace the error page configuration with custom_404.html
sudo sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /etc/nginx/sites-available/default

# Restart Nginx service to apply the changes
sudo service nginx restart

# Verify the presence of custom_404.html and check if it returns 404 status
content=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/custom_404.html)

# Output the HTTP status code for verification
echo "HTTP Status Code for custom_404.html: $content"

