#!/bin/bash

# Specify the server address and private key file path
server_address="8.8.8.8"  # Replace with your actual server address
private_key_file="$HOME/.ssh/school"

# Use ssh with appropriate flags for user and identity file
ssh -i "$private_key_file" "$server_address"
